In [8]:
import pandas as pd
import numpy as np
import openpyxl
pd.set_option('display.max_colwidth', 200)

In [9]:
def get_1st_item(s):
    str_corr = s[36:44]
    #  去掉下面不需要字符
    result = str_corr.strip('u},\'\'').replace(',','').replace('}','').replace('{','').replace('\'','').replace('u','').replace(' ','')
    
    return result

def read_file(filepath):
    df = pd.read_csv(filepath,encoding='utf-8')
    df.drop(df.columns[[0,1,3]], inplace=True, axis=1) # inplace=True 表示在本df修改 不需要再赋值
    return df
"""
jmc-76s.csv  jmc-result-508s.csv
qc-73s.csv  qc-result-492s.csv
qincai-74s.csv   qincai-result-525s.csv
"""
df = pd.read_csv('dataset/jmc-76s.csv', encoding='utf-8')

# df.drop(df.columns[[0,1,3]], inplace=True, axis=1) # inplace=True 表示在本df修改 不需要再赋值
df

In [10]:
def get_df_by_series(series):
    dataframe  =  pd.DataFrame(data=series, columns=['result'])
    return dataframe

In [11]:
seri = df.result.apply(get_1st_item)
# print (type(df1))
df2 = get_df_by_series(seri)

#  把df写入excel中
# writer = pd.ExcelWriter('test.xlsx')
# df2.to_excel(writer,'Sheet1')
# writer.save()

In [12]:
# df2.groupby('result').unique()
# df2.result.unique()   #返回 result列 取值
# df2.result.count()    # 返回result列行数
df2.groupby('result').apply(lambda x : x.describe())  # 返回本列各取值的describe()

              result
result
小香菜    count      64
       unique      1
       top       小香菜
       freq       64
样芹菜    count     256
       unique      1
       top       样芹菜
       freq      256
芥菜     count       4
       unique      1
       top        芥菜
       freq        4
芹菜     count      70
       unique      1
       top        芹菜
       freq       70
苦菊     count       1
       unique      1
       top        苦菊
       freq        1
西芹     count       1
       unique      1
       top        西芹
       freq        1
非果蔬食材  count     260
       unique      1
       top     非果蔬食材
       freq      260